version: '3.8'

services:
  ai-minecraft-bot:
    build: .
    container_name: ai-minecraft-bot
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERVER_IP=${SERVER_IP:-localhost}
      - PORT=${PORT:-19132}
      - BOT_NAME=${BOT_NAME:-AI_Admin}
      - DEBUG_MODE=${DEBUG_MODE:-true}
    volumes:
      # Mount logs directory for persistence
      - ./logs:/usr/src/app/logs
      # Mount structures directory for persistence  
      - ./structures:/usr/src/app/structures
    networks:
      - minecraft-network
    # Health check to ensure bot is running
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  minecraft-network:
    driver: bridge

# Optional: Add a simple web dashboard (future enhancement)
# services:
#   dashboard:
#     image: nginx:alpine
#     ports:
#       - "8080:80"
#     networks:
#       - minecraft-network 