version: '3.8'

services:
  ai-minecraft-bot:
    build: .
    container_name: ai-minecraft-bot
    restart: unless-stopped
    # Use host networking for direct access to localhost
    network_mode: host
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERVER_IP=localhost  # Can use localhost with host networking
      - PORT=19132
      - BOT_NAME=AI_Admin
      - DEBUG_MODE=true
    volumes:
      # Mount logs directory for persistence
      - ./logs:/usr/src/app/logs
      # Mount structures directory for persistence  
      - ./structures:/usr/src/app/structures
    # Health check to ensure bot is running
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Note: With host networking, the container uses the host's network stack directly
# This allows direct access to localhost services like your Minecraft server

# Optional: Add a simple web dashboard (future enhancement)
# services:
#   dashboard:
#     image: nginx:alpine
#     ports:
#       - "8080:80"

# Note: When using host networking, custom networks are not needed
# The container will use the host's network stack directly

# Optional: Add a simple web dashboard (future enhancement)
# services:
#   dashboard:
#     image: nginx:alpine
#     ports:
#       - "8080:80"
#     networks:
#       - minecraft-network 